# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: NCC 2016
email: mcmullen.greg@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Notes and additional information from the National Coaches Conference in Seattle, WA
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://gregoryamcmullen.com/" # the base hostname & protocol for your site
twitter_username: mcmullen_greg
github_username:  mcmullengreg

# Build settings
markdown: kramdown

permalink: /:categories/:title/
